### ISSUE TITLE
The default `borderWidth` unit (px)  is the wrong choice.

### ISSUE THREAD

**Issue by setanarut** [shellscape/vscode-shellscape-brackets#2]
By default the unit `em` (font size relative) should be used instead of the `px` (absolute). It looks ugly at small font sizes. For example, 3 pixels will look good at large font sizes, but ugly at small font sizes:

```json
"borderWidth": "3px",
```
![Ekran Resmi 2023-12-26 02 52 51](https://github.com/shellscape/vscode-shellscape-brackets/assets/36481442/5d519e04-e6c5-41e8-aa75-9c2d1870feda)

This way it is always adjusted according to the font size:
```json
"borderWidth": "0.1em",
```

![Ekran Resmi 2023-12-26 03 11 11](https://github.com/shellscape/vscode-shellscape-brackets/assets/36481442/734f0aee-4d93-462a-a95e-07c81811c575)

**Comment by shellscape** [comment]
This is an opinionated extension that's designed to mimic the default appearance on Atom.

Please feel free to fork this to suit your needs.

**Comment by setanarut** [comment]
> This is an opinionated extension that's designed to mimic the default appearance on Atom.
> 
> Please feel free to fork this to suit your needs.

Who cares what the Atom looks like. It's a bug. Bigot.

**Comment by setanarut** [comment]
I don't even think atom has such a bug. moron

**Comment by shellscape** [comment]
You must be fun at parties

**Comment by denzilv** [comment]
I actually think it looks better as pixels. 🤙

**Comment by siddarthkay** [comment]
> I don't even think atom has such a bug. moron

How not to open source 101 👏

**Comment by Greek** [comment]
zzz

**Comment by Nikolai-Grytvik-Borbe** [comment]
![image](https://github.com/shellscape/vscode-shellscape-brackets/assets/107432990/4126613d-ba98-44d8-aafe-030b5c42455b)

I agere with Setanarus
